const questionBank = {
  "Frontend Developer": {
    Beginner: [
      "What is the difference between HTML, CSS, and JavaScript?",
      "What are semantic HTML elements?",
      "What is the difference between id and class in HTML?",
      "What is the CSS box model?",
      "What is the difference between margin and padding?",
      "What is responsive web design?",
      "What is the difference between let, const, and var?",
      "What are JavaScript data types?",
      "What is the difference between == and ===?",
      "What is a function in JavaScript?",
      "What is an array in JavaScript?",
      "What is an object in JavaScript?",
      "What is DOM?",
      "What is event handling in JavaScript?",
      "What is the difference between null and undefined?",
    ],

    Intermediate: [
      "Explain event bubbling and event capturing in JavaScript.",
      "What are closures in JavaScript?",
      "Explain promises in JavaScript.",
      "What is async/await?",
      "What is the JavaScript event loop?",
      "Explain localStorage, sessionStorage, and cookies.",
      "What is debouncing?",
      "What is throttling?",
      "What is destructuring in JavaScript?",
      "What are higher-order functions?",
      "Explain the spread and rest operators.",
      "What is the difference between map(), filter(), and reduce()?",
      "What is CORS?",
      "What is an API?",
      "How does a browser render a webpage?",
    ],

    Advanced: [
      "How would you optimize the performance of a large frontend application?",
      "Explain critical rendering path optimization.",
      "How does browser caching improve performance?",
      "What is code splitting?",
      "Explain lazy loading in frontend applications.",
      "How would you prevent unnecessary API requests?",
      "How would you handle state management in a large application?",
      "Explain memory leaks in JavaScript.",
      "How does garbage collection work in JavaScript?",
      "How would you improve the Core Web Vitals of a website?",
    ],
  },

  "React Developer": {
    Beginner: [
      "What is React?",
      "What are components in React?",
      "What are props in React?",
      "What is state in React?",
      "What is JSX?",
      "What is the difference between props and state?",
      "What is useState?",
      "What is useEffect?",
      "Why do we use keys in React lists?",
      "What is conditional rendering?",
    ],

    Intermediate: [
      "Explain the Virtual DOM.",
      "What is the difference between controlled and uncontrolled components?",
      "Explain useMemo and useCallback.",
      "What is React Context API?",
      "What are custom hooks?",
      "Explain React component lifecycle.",
      "How does React handle events?",
      "What is prop drilling?",
      "How can prop drilling be avoided?",
      "What is React Router?",
    ],

    Advanced: [
      "How would you optimize a large React application?",
      "Explain React reconciliation.",
      "How does React Fiber work?",
      "How would you design scalable state management?",
      "How would you prevent unnecessary React re-renders?",
      "Explain code splitting and lazy loading in React.",
      "How would you architect a production React application?",
      "How would you optimize a React application with thousands of components?",
    ],
  },

  "JavaScript Developer": {
    Beginner: [
      "What is JavaScript?",
      "What are primitive data types in JavaScript?",
      "What is the difference between var, let, and const?",
      "What is a function?",
      "What is an array?",
      "What is an object?",
      "What is the difference between == and ===?",
      "What is DOM manipulation?",
      "What are arrow functions?",
      "What is JSON?",
    ],

    Intermediate: [
      "Explain closures in JavaScript.",
      "Explain promises.",
      "What is async/await?",
      "Explain the event loop.",
      "What are callbacks?",
      "What is callback hell?",
      "Explain hoisting.",
      "What is the prototype chain?",
      "What are higher-order functions?",
      "Explain debouncing and throttling.",
    ],

    Advanced: [
      "Explain the JavaScript execution context.",
      "How does garbage collection work?",
      "Explain microtasks and macrotasks.",
      "How would you optimize a JavaScript application?",
      "Explain memory leaks in JavaScript.",
      "What are Web Workers?",
      "How does JavaScript handle concurrency?",
      "Explain event delegation.",
    ],
  },

  "Backend Developer": {
    Beginner: [
      "What is backend development?",
      "What is an API?",
      "What is REST API?",
      "What is HTTP?",
      "What is a database?",
      "What is CRUD?",
      "What is authentication?",
      "What is authorization?",
      "What is JSON?",
      "What is middleware?",
    ],

    Intermediate: [
      "What is the difference between authentication and authorization?",
      "Explain REST API principles.",
      "What are HTTP status codes?",
      "What is JWT authentication?",
      "What is database indexing?",
      "What is middleware?",
      "What is API rate limiting?",
      "What is CORS?",
      "What is SQL injection?",
      "How do you secure an API?",
    ],

    Advanced: [
      "How would you design a scalable REST API?",
      "How would you handle millions of API requests?",
      "How would you design authentication for a large application?",
      "Explain database sharding.",
      "Explain database replication.",
      "How would you implement API rate limiting?",
      "How would you design a microservices architecture?",
      "How would you improve backend performance?",
    ],
  },

  "Node.js Developer": {
    Beginner: [
      "What is Node.js?",
      "Why is Node.js used for backend development?",
      "What is npm?",
      "What is Express.js?",
      "What is middleware in Express?",
      "How do you create a REST API using Node.js?",
      "What is package.json?",
      "What is the difference between dependencies and devDependencies?",
      "What is req and res in Express?",
    ],

    Intermediate: [
      "Explain the Node.js event loop.",
      "What are streams in Node.js?",
      "What is middleware in Express.js?",
      "How does asynchronous programming work in Node.js?",
      "What is JWT authentication in Node.js?",
      "How do you handle errors in Express?",
      "How do you connect Node.js with MongoDB?",
      "What is clustering in Node.js?",
      "How do you secure a Node.js API?",
    ],

    Advanced: [
      "How would you scale a Node.js application?",
      "How would you handle millions of concurrent connections?",
      "How would you optimize a Node.js API?",
      "Explain Node.js worker threads.",
      "How would you design a production-ready Node.js backend?",
      "How would you implement caching in Node.js?",
    ],
  },

  "Java Developer": {
    Beginner: [
      "What is Java?",
      "What is a class in Java?",
      "What is an object?",
      "What is inheritance?",
      "What is polymorphism?",
      "What is encapsulation?",
      "What is abstraction?",
      "What is a constructor?",
      "What is method overloading?",
      "What is method overriding?",
    ],

    Intermediate: [
      "Explain the four pillars of OOP.",
      "What is the difference between an interface and abstract class?",
      "Explain exception handling in Java.",
      "What is the Java Collection Framework?",
      "What is HashMap?",
      "What is multithreading?",
      "What is the difference between String and StringBuilder?",
      "What is garbage collection in Java?",
      "What are Java Streams?",
    ],

    Advanced: [
      "How would you design a scalable Java backend?",
      "Explain JVM architecture.",
      "How does Java garbage collection work?",
      "How would you optimize a Java application?",
      "Explain thread synchronization.",
      "How would you design a high-performance Java API?",
    ],
  },

  "Python Developer": {
    Beginner: [
      "What is Python?",
      "What are lists in Python?",
      "What are tuples?",
      "What are sets?",
      "What are dictionaries?",
      "What is a Python function?",
      "What is a module?",
      "What is a package?",
      "What is exception handling?",
    ],

    Intermediate: [
      "Explain decorators in Python.",
      "What are generators?",
      "What is list comprehension?",
      "Explain lambda functions.",
      "What is the difference between shallow copy and deep copy?",
      "What are Python virtual environments?",
      "How does Python handle memory management?",
      "What is the Global Interpreter Lock?",
    ],

    Advanced: [
      "How would you optimize a Python application?",
      "How would you process millions of records using Python?",
      "Explain multiprocessing vs multithreading.",
      "How would you design a scalable Python backend?",
      "How would you optimize database operations in Python?",
    ],
  },

  "Full Stack Developer": {
    Beginner: [
      "What is the difference between frontend and backend?",
      "What is a database?",
      "What is an API?",
      "What is REST API?",
      "What is authentication?",
      "What is CRUD?",
      "What is HTTP?",
      "What is JSON?",
      "What is Git?",
      "What is responsive design?",
    ],

    Intermediate: [
      "How does a request travel from React to a backend API?",
      "How does a frontend communicate with MongoDB?",
      "How does JWT authentication work?",
      "What is CORS?",
      "How would you structure a full-stack project?",
      "How do you protect backend routes?",
      "How do you handle API errors?",
      "How do you deploy a full-stack application?",
    ],

    Advanced: [
      "How would you architect a scalable full-stack application?",
      "How would you secure a production full-stack application?",
      "How would you handle millions of users?",
      "How would you design authentication and authorization?",
      "How would you optimize frontend and backend performance?",
      "How would you design a scalable database architecture?",
    ],
  },
};

export default questionBank;
